update to use high res static data. NOTE LAKE DEPTH REMOVED.

diff --git a/rasp-from-scratch/rasp/Dockerfile b/rasp-from-scratch/rasp/Dockerfile
--- a/rasp-from-scratch/rasp/Dockerfile
+++ b/rasp-from-scratch/rasp/Dockerfile
@@ -71,17 +71,23 @@ RUN cd $BASEDIR && tar xf geog.tar.gz \
   && geogrid.exe 
 
 
-  # Verify that geogrid generated the expected output files for 2 domains
+  # Verify that geogrid generated the expected output files for 2 domains, print log if missing
 RUN if [ ! -f "$BASEDIR/${REGION}/geo_em.d01.nc" ]; then \
-  echo "ERROR: geo_em.d01.nc was not generated by geogrid.exe" && exit 1; \
+      echo "ERROR: geo_em.d01.nc was not generated by geogrid.exe"; \
+      echo "---- geogrid.log ----"; \
+      cat "$BASEDIR/${REGION}/geogrid.log" || true; \
+      exit 1; \
     fi \
   && if [ ! -f "$BASEDIR/${REGION}/geo_em.d02.nc" ]; then \
-  echo "ERROR: geo_em.d02.nc was not generated by geogrid.exe" && exit 1; \
+      echo "ERROR: geo_em.d02.nc was not generated by geogrid.exe"; \
+      echo "---- geogrid.log ----"; \
+      cat "$BASEDIR/${REGION}/geogrid.log" || true; \
+      exit 1; \
     fi \
   && echo "SUCCESS: geogrid output files geo_em.d01.nc and geo_em.d02.nc generated correctly"
 
 
-RUN  rm -rf $BASEDIR/geog $BASEDIR/geog.tar.gz
+  RUN  rm -rf $BASEDIR/geog $BASEDIR/geog.tar.gz
 
 # Add rasp assets (WRF glue scripts, plot scripts, DrJack library, custom stuff) and the rest of the region folder
 # Do this afterwards so we do not trigger the copying and extraction of geog data each time we change scripts or namelist.input settings
@@ -91,7 +97,11 @@ COPY GM/ $BASEDIR/GM/
 COPY logo.svg $BASEDIR/
 COPY ncl_jack/ncl_jack_fortran.so $BASEDIR/GM/LIB/
 COPY ncl_jack/libncl_jack.nocuda.so ncl_jack/libwrf_user.nocuda.so $BASEDIR/lib/
+# Preserve geo_em files created by geogrid before copying region directory (if they exist)
+RUN mkdir -p /tmp/geo_em_backup && [ -f $BASEDIR/${REGION}/geo_em.d01.nc ] && cp $BASEDIR/${REGION}/geo_em.*.nc /tmp/geo_em_backup/ || true
 COPY ${REGION}/ $BASEDIR/${REGION}/
+# Restore the geo_em files (if they were backed up)
+RUN [ -f /tmp/geo_em_backup/geo_em.d01.nc ] && cp /tmp/geo_em_backup/geo_em.*.nc $BASEDIR/${REGION}/ || true && rm -rf /tmp/geo_em_backup
 RUN cp ${REGION}/namelist.input ${REGION}/namelist.input.template \
   && mv $BASEDIR/${REGION}/rasp.region_data.ncl $BASEDIR/${REGION}/sitedata.ncl $BASEDIR/GM/
 
